### ISSUE TITLE
Add fields to Application Form 

### ISSUE THREAD

**Issue by dribblecastle** [FriendToFriend/Revision_1.0.0#16]
Please add/make the following changes to the application form.    These changes will allow us to more closely match the updated PDF form created in March 2015 

PDF = http://www.friendtofriendamerica.org/VolunteerApplication.pdf
WEB = http://friendtofriendamerica.org/FTFtest/volunteerApp.php

Question = Reference #1 + #2 
     Need to add email field 

Question = Check any interests and/or skills that you have:
     Add other field: short or long text field.   (low priority) 

Question = Do you have a preference for when you would volunteer?
     Add mornings checkbox  

Question = How did you hear about Friend to Friend America?
    add VolunteerMatch.com to pull down menu
    add “other” field in addition to the pull down menu  - short text field

**Comment by timcuster** [comment]
Alpha,

Assigning to you, but let me know if you need new fields.

TLC

**Comment by alphad05** [comment]
Done
